# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "pathogen_name", # <get_cases_plot>
  "age_group", # <get_cases_plot>
  "end_of_week_reference_date", # <get_cases_plot>
  "season", # <get_cases_plot>
  "count", # <get_cases_plot>
  "end_of_week_reference_date", # <get_delay_over_time_plot>
  "pathogen_name", # <get_delay_over_time_plot>
  "age_group", # <get_delay_over_time_plot>
  "season", # <get_delay_over_time_plot>
  "count", # <get_delay_over_time_plot>
  "delay", # <get_delay_over_time_plot>
  "mean_delay", # <get_delay_over_time_plot>
  "end_of_week_reference_date", # <get_violin_plot_delay>
  "pathogen_name", # <get_violin_plot_delay>
  "age_group", # <get_violin_plot_delay>
  "season", # <get_violin_plot_delay>
  "count", # <get_violin_plot_delay>
  "delay", # <get_violin_plot_delay>
  "mean_delay", # <get_violin_plot_delay>
  "reference_date", # <get_weekly_data>
  "report_date", # <get_weekly_data>
  "wday_reference", # <get_weekly_data>
  "wday_report", # <get_weekly_data>
  "epiyear_ref", # <get_weekly_data>
  "epiweek_ref", # <get_weekly_data>
  "epiyear_rep", # <get_weekly_data>
  "epiweek_rep", # <get_weekly_data>
  "pathogen", # <get_weekly_data>
  "age_group", # <get_weekly_data>
  "count", # <get_weekly_data>
  "end_of_week_report_date", # <get_weekly_data>
  "end_of_week_reference_date", # <get_weekly_data>
  "delay", # <clean_data>
  "end_of_week_reference_date", # <clean_data>
  "age_group", # <clean_data>
  NULL
))
